# https://www.codewars.com/kata/567bf4f7ee34510f69000032

# Implement a function which should return true if given object is a digit (0-9), false otherwise.

import re

def is_digit(n):
    return bool(re.fullmatch("^\d$", n))
    
import codewars_test as test
from solution import is_digit

@test.describe("Fixed Tests")
def fixed_tests():
    @test.it('Basic Test Cases')
    def basic_test_cases():
        test.assert_equals(is_digit(""), False)
        test.assert_equals(is_digit("7"), True)
        test.assert_equals(is_digit(" "), False)
        test.assert_equals(is_digit("a"), False)
        test.assert_equals(is_digit("a5"), False)
        test.assert_equals(is_digit("14"), False)
        test.assert_equals(is_digit(" "), False)
        test.assert_equals(is_digit("!"), False)
        test.assert_equals(is_digit("\""), False)
        test.assert_equals(is_digit("#"), False)
        test.assert_equals(is_digit("$"), False)
        test.assert_equals(is_digit("%"), False)
        test.assert_equals(is_digit("&"), False)
        test.assert_equals(is_digit("'"), False)
        test.assert_equals(is_digit("("), False)
        test.assert_equals(is_digit(")"), False)
        test.assert_equals(is_digit("*"), False)
        test.assert_equals(is_digit("+"), False)
        test.assert_equals(is_digit(","), False)
        test.assert_equals(is_digit("-"), False)
        test.assert_equals(is_digit("."), False)
        test.assert_equals(is_digit("/"), False)
        test.assert_equals(is_digit("0"), True)
        test.assert_equals(is_digit("1"), True)
        test.assert_equals(is_digit("2"), True)
        test.assert_equals(is_digit("3"), True)
        test.assert_equals(is_digit("4"), True)
        test.assert_equals(is_digit("5"), True)
        test.assert_equals(is_digit("6"), True)
        test.assert_equals(is_digit("7"), True)
        test.assert_equals(is_digit("8"), True)
        test.assert_equals(is_digit("9"), True)
        test.assert_equals(is_digit(":"), False)
        test.assert_equals(is_digit(";"), False)
        test.assert_equals(is_digit("<"), False)
        test.assert_equals(is_digit("="), False)
        test.assert_equals(is_digit(">"), False)
        test.assert_equals(is_digit("?"), False)
        test.assert_equals(is_digit("@"), False)
        test.assert_equals(is_digit("A"), False)
        test.assert_equals(is_digit("B"), False)
        test.assert_equals(is_digit("C"), False)
        test.assert_equals(is_digit("D"), False)
        test.assert_equals(is_digit("E"), False)
        test.assert_equals(is_digit("F"), False)
        test.assert_equals(is_digit("G"), False)
        test.assert_equals(is_digit("H"), False)
        test.assert_equals(is_digit("I"), False)
        test.assert_equals(is_digit("J"), False)
        test.assert_equals(is_digit("K"), False)
        test.assert_equals(is_digit("L"), False)
        test.assert_equals(is_digit("M"), False)
        test.assert_equals(is_digit("N"), False)
        test.assert_equals(is_digit("O"), False)
        test.assert_equals(is_digit("P"), False)
        test.assert_equals(is_digit("Q"), False)
        test.assert_equals(is_digit("R"), False)
        test.assert_equals(is_digit("S"), False)
        test.assert_equals(is_digit("T"), False)
        test.assert_equals(is_digit("U"), False)
        test.assert_equals(is_digit("V"), False)
        test.assert_equals(is_digit("W"), False)
        test.assert_equals(is_digit("X"), False)
        test.assert_equals(is_digit("Y"), False)
        test.assert_equals(is_digit("Z"), False)
        test.assert_equals(is_digit("["), False)
        test.assert_equals(is_digit("\\"), False)
        test.assert_equals(is_digit("]"), False)
        test.assert_equals(is_digit("^"), False)
        test.assert_equals(is_digit("_"), False)
        test.assert_equals(is_digit("`"), False)
        test.assert_equals(is_digit("a"), False)
        test.assert_equals(is_digit("b"), False)
        test.assert_equals(is_digit("c"), False)
        test.assert_equals(is_digit("d"), False)
        test.assert_equals(is_digit("e"), False)
        test.assert_equals(is_digit("f"), False)
        test.assert_equals(is_digit("g"), False)
        test.assert_equals(is_digit("h"), False)
        test.assert_equals(is_digit("i"), False)
        test.assert_equals(is_digit("j"), False)
        test.assert_equals(is_digit("k"), False)
        test.assert_equals(is_digit("l"), False)
        test.assert_equals(is_digit("m"), False)
        test.assert_equals(is_digit("n"), False)
        test.assert_equals(is_digit("o"), False)
        test.assert_equals(is_digit("p"), False)
        test.assert_equals(is_digit("q"), False)
        test.assert_equals(is_digit("r"), False)
        test.assert_equals(is_digit("s"), False)
        test.assert_equals(is_digit("t"), False)
        test.assert_equals(is_digit("u"), False)
        test.assert_equals(is_digit("v"), False)
        test.assert_equals(is_digit("w"), False)
        test.assert_equals(is_digit("x"), False)
        test.assert_equals(is_digit("y"), False)
        test.assert_equals(is_digit("z"), False)
        test.assert_equals(is_digit("{"), False)
        test.assert_equals(is_digit("|"), False)
        test.assert_equals(is_digit("}"), False)
        test.assert_equals(is_digit("~"), False)
        test.assert_equals(is_digit("1\n0"), False)
        test.assert_equals(is_digit("1\n"), False)
        test.assert_equals(is_digit("1 "), False)
        test.assert_equals(is_digit(" 1"), False)
